### PR TITLE
64DD disk loading support for SummerCart64

### PR DESCRIPTION
**Pull request by Polprzewodnikowy**
## Types of changes

- [ ] Improvement (non-breaking change that adds a new feature)
- [ ] Bug fix (fixes an issue)
- [ ] Breaking change (breaking change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>

### CODE REVIEW

**Comment by networkfusion** [comment]
Am I right in saying that https://github.com/Polprzewodnikowy/SummerCart64/releases/tag/v2.17.0 has breaking changes for the "main" branch of the N64FlashcartMenu? It "might" be worth mentioning that in the release notes (not that anyone ever reads them). But good work on the NDD loading, I am now running that branch and can also load 64DD disks, although most of the cart roms now fail to load, but given this PR is still draft, I guess  that is to be expected.

**Comment by networkfusion** [comment]
#50 targets this branch, just to help with the docs.

**Comment by Polprzewodnikowy** [comment]
New firmware didn't introduce breaking changes. Loading menu on v2.16.0 and older was always broken due to libcart way of handling PI timings. At init libcart always read PI config from address `0x10000000` and applied those timings when calling `cart_init` function. Old firmware loaded menu ROM directly to the N64 RDRAM and data in SDRAM was garbage, especially that important value at `0x10000000`. New firmware menu loading works identical to the EverDrive-64 and 64drive method - data is loaded to the SDRAM and reboot code is used so libcart isn't going to read garbage PI settings anymore. As a bonus we can now use data in ROM without doing manual injection. I might revise font loading code to use dragonfs instead.

I've changed supported firmware version in `sc64.c` and that force the users to update the firmware. Older firmware didn't support "writable" flag for 64DD disk mapping anyways and FW update is necessary.

**Comment by Polprzewodnikowy** [comment]
Also I don't see any issues mentioned before about issues with loading ROMs. That works perfectly fine for me, even BB2000 loads without issue. (USA ROMs and NTSC console)

**Comment by networkfusion** [comment]
> Also I don't see any issues mentioned before about issues with loading ROMs. That works perfectly fine for me, even BB2000 loads without issue. (USA ROMs and NTSC console)

Interesting, I do seem to have problems with BB2000 NTSC, with just getting a blank screen. I will see if I can chase the issue when I next have a chance.

**Comment by Polprzewodnikowy** [comment]
I have the loading problem now after updating libdragon to the latest version. My guess is that some HW is not properly uninitialized and that causes issues with some games. I'm going to investigate this now.

**Comment by Polprzewodnikowy** [comment]
There's a lot of changes since last update: https://github.com/DragonMinded/libdragon/compare/352679922bad5403f8ea4b9123dfe0403d030bc2...dd2202a6082cd3d92f4c22e64b27f148612c4c3a

**Comment by Polprzewodnikowy** [comment]
@networkfusion I've decided to remove RDRAM reset from reboot and change boot type to NMI as this seems to be much less problematic than forcing cold boot. Can you check if there are still problems with loading some games?

**Comment by networkfusion** [comment]
> @networkfusion I've decided to remove RDRAM reset from reboot and change boot type to NMI as this seems to be much less problematic than forcing cold boot. Can you check if there are still problems with loading some games?

I have tested BB2000 and BattleTanx and BattleTanks GA (along with a few others) and they boot fine. On one occasion BattleTanks GA did not return to the menu and showed a bunch of horizontal lines, but I have not been able to repro.

I also note the display corruption on reboot, but I know you are aware of that.

**Pull request merged**
