### PR TITLE
Add emulator smoke tests

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

Shows how we can leverage the CI to run emulated smoke tests.
It is only currently compatible with Ares V131 (since later versions remove Vulkan).
Iit shows (and uploads) the `No Flashcart was detected` screen and associated log from ares.

## Motivation and Context

We should support smoke tests at some point.

## Types of changes

- [ ] Improvement (non-breaking change that adds a new feature)
- [ ] Bug fix (fixes an issue)
- [ ] Breaking change (breaking change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>

### CODE REVIEW

**Comment by networkfusion** [comment]
I have fixed the PR and underlying screenshot action (although have not fully resolved the deperecation notice with this PR).

**Comment by networkfusion** [comment]
Rebased to fatfs-begone.

**Comment by Polprzewodnikowy** [comment]
Surprised this even works considering no vulkan support on the github runner. For better screenshot quality you'd want to enable weave deinterlacing in the ares settings, not sure if this option existed in v131 though.

**Comment by networkfusion** [comment]
> Surprised this even works considering no vulkan support on the github runner. For better screenshot quality you'd want to enable weave deinterlacing in the ares settings, not sure if this option existed in v131 though.

This (I think) was the last version of ares to work without vulkan. Depending on needs, this PR might be totally obsolete (i.e. will no longer work), or workable to an extent.

**Comment by Polprzewodnikowy** [comment]
As a workaround we can use our own runner that can has vulkan https://github.com/Polprzewodnikowy/N64FlashcartMenu/settings/actions/runners
But this is obviously not sustainable in a long term. I wonder if M1 Mac runners have GPU enabled, might be worth testing.

**Comment by networkfusion** [comment]
That one seems private to me... But know what you mean. I dont mind also having a local runner for my SC64, if it helps at all (since using it at the moment is irregular at best).

**Comment by networkfusion** [comment]
@Polprzewodnikowy 
image

😁 Note that I had to change the libdragon branch to preview and update the submodule, as I think that your local runner presumes it...

**Comment by networkfusion** [comment]
For "true" support, this PR will be dependent on https://github.blog/changelog/2023-10-31-run-your-ml-workloads-on-github-actions-with-gpu-runners/

**Pull request closed without merging**
