### PR TITLE
Menu improvements

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

This PR adds docfx to the CI to target documentation for the N64FlashcartMenu and updates the libdragon submodule.
It also adds a number of menu improvements.

## Motivation and Context

Will eventually stop us from being lazy, however as the project is very much WiP,
Currently the CI only runs it to show what warnings need to be "fixed".
In future, it needs to "error" when things are incorrect AND deploy to the WIKI.

## How Has This Been Tested?

Builds on my fork.

## Screenshots

image

## Types of changes

- [ ] Improvement (non-breaking change that adds a new feature)
- [ ] Bug fix (fixes an issue)
- [ ] Breaking change (breaking change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>

### CODE REVIEW

**Comment by networkfusion** [comment]
Sorry for the extra commits that make this PR unclean. It is currently difficult to work on multiple branches until my PR for libdragon handling auto generated files is commited.

**Comment by Polprzewodnikowy** [comment]
I think there should be a stopping point in this PR as it bloated way past initial scope and merging it with my changes gonna be a nightmare.
I gonna have some time in couple of days so I could check the code and resolve conflicts with my commit.
As a bonus I've already rewritten all browser drawing code to use RDP and `rdpq_font` capabilities as shown on screenshots below.
Screenshot 2023-07-07 00-09-32
Screenshot 2023-07-07 00-09-49
Screenshot 2023-07-07 00-14-15
(Fuzziness on the image is due to 640x480 interlaced mode)

**Comment by networkfusion** [comment]
Amazing... I do get carried away some times and should have stopped when my PR worked for the libdragon submodule working properly,

I have "tried" to keep each checkin automic but some of them were not.

Apart from the issues with file endian for some of my ROM's all the menu works as expected with this PR.

I await your changes before I further update again.

**Comment by networkfusion** [comment]
Just adding the following improvement outcomes:
image
This shows the necessary N64 ROM info AFAIC.. and Z-OT is great because it id expandable.

Another that shows an Aleck64 ROM:
image


To the average user, System info can be important:
image

Quite interesting because this displays correctly on my TV using composite:
image
but time is wrapping on my capture card (which is also composite!).

**Comment by networkfusion** [comment]
And here is an endian issue (which I hope you have solved...
image

**Comment by Polprzewodnikowy** [comment]
Gonna megre it as is for now so you can continue work. I've resolved conflicts but most of the changes inside `browser.c` were discarded due to new version using rdpq.
Few notes regarding some specifics due to how SC64 loads menu:
 - Menu never ends up in ROM space so we can't use anything that loads data from ROM. DragonFS is unusable in such conditions.
 - Because of above I've created `assets.c` for embedding binaries directly into memory.
 - For now it's only used for loading font data but it can be extended for other things.
 - But beware - some libdragon APIs can't work with this hack, for example `wav64_open` can work only with data directly inside ROM space.
 - Workaround for this can be created so if we ever end up adding sound effects for the menu I could write it.

**Pull request merged**
